CREATE TABLE NOVA_PRODUTOS (
    ID_PRODUTO INT NOT NULL,
	CODIGO VARCHAR(255),
    NOME VARCHAR(255) COLLATE Latin1_General_CI_AS NOT NULL,
    VALOR_DE_VENDA FLOAT NOT NULL,
    VALOR_DE_CUSTO FLOAT NOT NULL,
    DESCRICAO TEXT COLLATE Latin1_General_CI_AS NULL,
    FOTO VARBINARY(MAX) NULL,
    QUANTIDADE INT NULL,
    ID_USUARIO INT NULL,
    CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID_PRODUTO)
);

INSERT INTO NOVA_PRODUTOS (ID_PRODUTO, NOME, VALOR_DE_VENDA, VALOR_DE_CUSTO, DESCRICAO, FOTO, QUANTIDADE, ID_USUARIO)
SELECT Id, Nome, Valor, 0, Descricao, Foto, QUANTIDADE, UsuarioId
FROM PRODUTOS;

DROP TABLE PRODUTOS

EXEC sp_rename 'NOVA_PRODUTOS', 'PRODUTOS';

GO

ALTER TABLE [dbo].[ProdutoVenda]  WITH CHECK ADD  CONSTRAINT [FK_ProdutoVenda_Produtos] FOREIGN KEY([ProdutoId])
REFERENCES [dbo].[PRODUTOS] ([ID_PRODUTO])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[ProdutoVenda] CHECK CONSTRAINT [FK_ProdutoVenda_Produtos]
GO

ALTER TABLE [dbo].[Produtos] ADD  DEFAULT ((0)) FOR [VALOR_DE_CUSTO]
GO

ALTER TABLE [dbo].[Produtos]  WITH CHECK ADD  CONSTRAINT [FK_Produtos_Usuarios] FOREIGN KEY([ID_USUARIO])
REFERENCES [dbo].[Usuarios] ([Id])
GO

ALTER TABLE [dbo].[Produtos] CHECK CONSTRAINT [FK_Produtos_Usuarios]
GO

ALTER TABLE [dbo].[Produtos] ADD  DEFAULT ((0)) FOR [QUANTIDADE]
GO

ALTER TABLE CONFIGURACAO
ADD PESQUISARPRODUTO DEFAULT 0;